name: clap_flikker
description: A Flutter app that detects clap sounds, turns on flashlight, and speaks a message.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  torch_light: ^1.0.0
  flutter_tts: ^3.8.3
  record: ^5.1.2  # For microphone audio stream and clap detection
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.2

dependency_overrides:
  record_linux: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
